# Этап 1
FROM erlang:21-alpine AS builder
WORKDIR /usr/src
COPY ./webRTP .
RUN apk update &&\
    apk upgrade &&\
    apk add --no-cache\
        make gcc\
        git
    
RUN rebar3 as prod release

# Этап 2
FROM alpine:3.15
WORKDIR /home/

RUN apk update &&\
    apk upgrade &&\
    apk add --no-cache\ 
            ortp-dev\
            bctoolbox-dev\
            libc-dev\
            make gcc\
            ffmpeg\
            openssl

RUN apk add --no-cache\ 
            py3-gtts\
            curl

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
        python3 get-pip.py &&\
        rm get-pip.py &&\
        pip install six

RUN mkdir -p webRTP/priv/voice
RUN mkdir webRTP/priv/db
RUN mkdir c_code

COPY --from=builder /usr/src/_build/prod/rel/webRTP /home/webRTP
COPY ./c_code /home/c_code
COPY ./database/abonents.json /home/webRTP/priv/db

RUN make -C /home/c_code

EXPOSE 80 5060
CMD ["/home/webRTP/bin/webRTP", "foreground"]